### ISSUE TITLE
iOS - BottomSheetHandler - view.Controller is null

### ISSUE THREAD

**Issue by michalkoch** [softlion/The49.Maui.BottomSheet#4]
Hi,
I try the sample on iOS 17.5.1 and after clicking on Modal sheet, it crash in PlatformMapSelectedDetent because view.Controller is null.

`[0:] An error occurred: 'Object reference not set to an instance of an object.'. Callstack: '   at The49.Maui.BottomSheet.BottomSheetHandler.PlatformMapSelectedDetent(BottomSheet view) in C:\Users\Michal\Downloads\The49.Maui.BottomSheet-main-fixed\src\Platforms\iOS\BottomSheetHandler.cs:line 18
   at The49.Maui.BottomSheet.BottomSheetHandler.MapSelectedDetent(BottomSheetHandler handler, BottomSheet view) in C:\Users\Michal\Downloads\The49.Maui.BottomSheet-main-fixed\src\BottomSheetHandler.cs:line 47
   at Microsoft.Maui.PropertyMapper`2.<>c__DisplayClass5_0[[The49.Maui.BottomSheet.BottomSheet, The49.Maui.BottomSheet, Version=8.0.6.0, Culture=neutral, PublicKeyToken=null],[The49.Maui.BottomSheet.BottomSheetHandler, The49.Maui.BottomSheet, Version=8.0.6.0, Culture=neutral, PublicKeyToken=null]].<Add>b__0(IElementHandler h, IElement v)
   at Microsoft.Maui.PropertyMapper.UpdatePropertyCore(String key, IElementHandler viewHandler, IElement virtualView)
   at Microsoft.Maui.PropertyMapper.UpdateProperties(IElementHandler viewHandler, IElement virtualView)
   at Microsoft.Maui.Handlers.ElementHandler.SetVirtualView(IElement view)
   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.IContentView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Platform.ContentView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SetVirtualView(IView view)
   at Microsoft.Maui.Handlers.ContentViewHandler.SetVirtualView(IView view)
   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.IContentView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Platform.ContentView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SetVirtualView(IElement view)
   at Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler)
   at Microsoft.Maui.Controls.Element.set_Handler(IElementHandler value)
   at Microsoft.Maui.Controls.VisualElement.set_Handler(IViewHandler value)
   at The49.Maui.BottomSheet.BottomSheet.ShowAsync(IWindow parent, Boolean animated, Boolean aboveEverything) in C:\Users\Michal\Downloads\The49.Maui.BottomSheet-main-fixed\src\BottomSheet.cs:line 107
   at The49.Maui.BottomSheet.BottomSheet.ShowAsync(Boolean animated, Boolean aboveEverything) in C:\Users\Michal\Downloads\The49.Maui.BottomSheet-main-fixed\src\BottomSheet.cs:line 80
   at The49.Maui.BottomSheet.Sample.MainPage.OpenModalSheet() in C:\Users\Michal\Downloads\The49.Maui.BottomSheet-main-fixed\sample\MainPage.xaml.cs:line 222
   at Microsoft.Maui.Controls.Command.<>c__DisplayClass4_0.<.ctor>b__0(Object o)
   at Microsoft.Maui.Controls.Command.Execute(Object parameter)
   at The49.Maui.BottomSheet.Sample.MainPage.list_SelectionChanged(Object sender, SelectionChangedEventArgs e) in C:\Users\Michal\Downloads\The49.Maui.BottomSheet-main-fixed\sample\MainPage.xaml.cs:line 581
   at Microsoft.Maui.Controls.SelectableItemsView.SelectionPropertyChanged(SelectableItemsView selectableItemsView, SelectionChangedEventArgs args)
   at Microsoft.Maui.Controls.SelectableItemsView.SelectedItemPropertyChanged(BindableObject bindable, Object oldValue, Object newValue)
   at Microsoft.Maui.Controls.BindableObject.OnBindablePropertySet(BindableProperty property, Object original, Object value, Boolean didChange, Boolean willFirePropertyChanged)
   at Microsoft.Maui.Controls.Element.OnBindablePropertySet(BindableProperty property, Object original, Object value, Boolean changed, Boolean willFirePropertyChanged)
   at Microsoft.Maui.Controls.BindableObject.SetValueActual(BindableProperty property, BindablePropertyContext context, Object value, Boolean currentlyApplying, SetValueFlags attributes, SetterSpecificity specificity, Boolean silent)
   at Microsoft.Maui.Controls.BindableObject.SetValueCore(BindableProperty property, Object value, SetValueFlags attributes, SetValuePrivateFlags privateAttributes, SetterSpecificity specificity)
   at Microsoft.Maui.Controls.BindableObject.SetValue(BindableProperty property, Object value)
   at Microsoft.Maui.Controls.SelectableItemsView.set_SelectedItem(Object value)
   at Microsoft.Maui.Controls.Handlers.Items.SelectableItemsViewController`1[[Microsoft.Maui.Controls.ReorderableItemsView, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].FormsSelectItem(NSIndexPath indexPath)
   at Microsoft.Maui.Controls.Handlers.Items.SelectableItemsViewController`1[[Microsoft.Maui.Controls.ReorderableItemsView, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].ItemSelected(UICollectionView collectionView, NSIndexPath indexPath)
   at Microsoft.Maui.Controls.Handlers.Items.SelectableItemsViewDelegator`2[[Microsoft.Maui.Controls.ReorderableItemsView, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Controls.Handlers.Items.ReorderableItemsViewController`1[[Microsoft.Maui.Controls.ReorderableItemsView, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].ItemSelected(UICollectionView collectionView, NSIndexPath indexPath)
   at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:line 61
   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:line 96
   at The49.Maui.BottomSheet.Sample.Program.Main(String[] args) in C:\Users\Michal\Downloads\The49.Maui.BottomSheet-main-fixed\sample\Platforms\iOS\Program.cs:line 13
   at System.Object.InvokeStub_Program.Main(Object , Span`1 )
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)'`

**Comment by t-macintosh** [comment]
I have this issue too.

**Comment by t-macintosh** [comment]
As a work-around to this, I've installed The49.Maui.BottomSheet 8.0.3 for iOS

```
<ItemGroup Condition="'$(TargetFramework)' == 'net9.0-ios'">
    <PackageReference Include="The49.Maui.BottomSheet" Version="8.0.3" />
</ItemGroup>
```

And installed Vapolia.The49.Maui.BottomSheet 8.0.4-ci-11839210783 for Android
```
<ItemGroup Condition="'$(TargetFramework)' == 'net9.0-android'">
    <PackageReference Include="Vapolia.The49.Maui.BottomSheet" Version="8.0.4-ci-11839210783" />
</ItemGroup>
```

Since the set up is all the same in the MauiProgram.cs file the changes above to the .csproj file should be all you need to change.

**Comment by softlion** [comment]
Hey ! I stopped upgrading that lib, as I was unable to fix the android issue with net9, and there is another lib in the wild which may work better. https://github.com/lucacivale/Maui.BottomSheet

You can still fork this repo and continue fixing.
I have hard time debugging iOS issues because of the stability of the debugger and visual studio, and I prefer not to anymore.
